format = """
$username\
[](bg:#3d59a1 fg:#a3aed2)\
$directory\
[](fg:#3d59a1 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260)\
\n$character"""

[username]
style_user = 'bg:#a3aed2 black'
format = '[  $user ]($style)'
disabled = false
show_always = true

[directory]
style = "fg:#e3e5e5 bg:#3d59a1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[character]
success_symbol = ' [](bold green)'
error_symbol = ' [✗](bold red)'
