[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#101017"
foreground = "#a9b1d6"

[terminal.shell]
program = "zsh"
args = ["-c", "~/.scripts/startup_terminal.sh; exec /bin/zsh"]

[window]
dynamic_padding   = false
resize_increments = true
opacity           = 0.95

[window.dimensions]
columns = 90
lines   = 25

[font]
size = 10.0

[font.bold]
family = "0xProto Nerd Font"
style  = "Heavy"

[font.bold_italic]
family = "0xProto Nerd Font"
style  = "Heavy Italic"

[font.italic]
family = "0xProto Nerd Font"
style  = "Medium Italic"

[font.normal]
family = "0xProto Nerd Font"
style  = "Medium"

[cursor.style]
shape = "Beam"
blinking = "On"

[env]
term = "xterm-256color"

[terminal]
